### PR TITLE
[FIX] Reconnect wait was not being honored

### LINKED ISSUE #290: Reconnect wait logic in java only waits if the current and last server tried are the same
https://github.com/nats-io/nats.java/blob/7f7fe824422b6966c8147bc5f028f228be4ed6ad/src/main/java/io/nats/client/impl/NatsConnection.java#L275-L278

This differs from go/other implementations.

### LINKED ISSUE #329: Issue in discovered server list in case of DNS entry
In the case of DNS as nats endpoint, while NATS producer/consumer discovering list the servers, Noticing  DNS entry also one of the servers discovered Servers list. This could an issue in case of if want to route the traffic from one cluster to another cluster in case of DR activity.

**Sample Log:**
``` Cnnected/ReConnected NATS Server: [tls://dns:4222, server1:4222, server2:4222,server3:4222, server4:4222, server5:4222] - Event :nats: connection opened ```

So the issue here, for example, if all the servers in the NATS clusters went down in the respective cluster. the produce/consumer is thinking DNS entry has a valid server and it keeps on trying and it is hanging there itself. and somehow producer/consumer always considering this DNS entry is healthy even though no active brokers in the clusters.

### PR DESCRIPTION
**Pull request by ColinSullivan1**
The reconnect wait option was not being honored.  Adjust the reconnect logic to honor it.

Partially resolves #329.
Resolves #290.

### CODE REVIEW

File: src/main/java/io/nats/client/impl/NatsConnection.java [hunk 1]
```diff
@@ -283,19 +286,17 @@ void reconnect() throws InterruptedException {
...
-                    this.reconnectWaiter = new CompletableFuture<>();
-                    waitForReconnectTimeout();
-                }
-
                 if (isDisconnectingOrClosed() || this.isClosing()) {
                     break;
                 }
 
+                if (server.equals(lastServer)) {
+                    shouldWait = true;
```
Comment (matthiashanel) [inline src/main/java/io/nats/client/impl/NatsConnection.java:294]: if we manage to connect, should shouldWait be set to false?
line 305

File: src/main/java/io/nats/client/impl/NatsConnection.java [hunk 2]
```diff
@@ -325,6 +326,11 @@ void reconnect() throws InterruptedException {
             if (maxTries > 0 && tries >= maxTries) {
                 break;
             }
+
+            if (shouldWait) {
```
Comment (matthiashanel) [inline src/main/java/io/nats/client/impl/NatsConnection.java:330]: shouldn't this happen inside the for loop? line 318 when we did not succeed or exceed the limits?

Comment (sasbury) [reply src/main/java/io/nats/client/impl/NatsConnection.java:330]: it is in the while loop, but i could see it going either way for sure

Comment (sasbury) [reply src/main/java/io/nats/client/impl/NatsConnection.java:330]: might be cleaner to move it up

File: src/main/java/io/nats/client/impl/NatsConnection.java (hunk 1 above)
Comment (sasbury) [reply src/main/java/io/nats/client/impl/NatsConnection.java:294]: i think so, otherwise it think we wait if we happen to connect to the last server

Comment (ColinSullivan1) [reply src/main/java/io/nats/client/impl/NatsConnection.java:294]: Yep, good catch, thanks.  I'll fix it, and move the delay up per other comments.

**Comment by ColinSullivan1** [comment]
Thanks for the reviews.  I moved the check into the loop.

**Comment by ColinSullivan1** [comment]
I have no clue why but can't trigger a re-run for the single flapping CI test.  Safe to merge IMO.

File: src/main/java/io/nats/client/impl/NatsConnection.java [hunk 3]
```diff
@@ -283,19 +285,13 @@ void reconnect() throws InterruptedException {
...
-                }
-
                 if (isDisconnectingOrClosed() || this.isClosing()) {
                     break;
                 }
 
                 updateStatus(Status.RECONNECTING);
 
                 tryToConnect(server, System.nanoTime());
-                lastServer = server;
```
Comment (matthiashanel) [inline src/main/java/io/nats/client/impl/NatsConnection.java:298]: Do I read this right, removing this line will bring the client in lie with other clients and fix #290

Comment (ColinSullivan1) [reply src/main/java/io/nats/client/impl/NatsConnection.java:298]: It should, yes.
